steps:
  - id: "decrypt-files"
    name: gcr.io/azoom-x/k8s-toolbox:1.0.3
    entrypoint: bash
    args:
      - -c
      - |
        sops -d ./deployments/${_ENV}/.env.sops.json > .env.json
  - id: build
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --dockerfile=./deployments/${_ENV}/Dockerfile
      - --destination=gcr.io/${PROJECT_ID}/${_APP_NAME}
      - --cache=true
      - --cache-ttl=6h
  - id: "deploy"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud beta run deploy ${_APP_NAME} \
          --platform managed \
          --region asia-northeast1 \
          --allow-unauthenticated \
          --image gcr.io/${PROJECT_ID}/${_APP_NAME} \
          --add-cloudsql-instances ${_INSTANCE_CONNECTION_NAME} \
          --set-env-vars INSTANCE-CONNECTION-NAME="${_INSTANCE_CONNECTION_NAME}"
substitutions:
  _ENV: production
  _APP_NAME: bengal-api
  _INSTANCE_CONNECTION_NAME: 'carparking-jp:asia-northeast1:carparking-db-prod'
